networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    image: nishaldevops/mongodb:v1
    container_name: mongodb
    networks:
    - roboshop

  catalogue:
    image: nishaldevops/catalogue:v1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb

  redis:
    image: redis
    container_name: redis
    networks:
    - roboshop

  user:
    image: nishaldevops/user:v1
    container_name: user
    networks:
    - roboshop
    depends_on:
      - mongodb
      - redis

  cart:
    image: nishaldevops/cart:v1
    container_name: cart
    networks:
    - roboshop
    depends_on:
      - mongodb
      - catalogue

  mysql:
    image: nishaldevops/mysql:v1
    container_name: mysql
    networks:
      - roboshop

  shipping:
    image: nishaldevops/shipping:v1
    container_name: shipping
    networks:
    - roboshop
    depends_on:
      - mysql
      - cart

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks: 
    - roboshop
    environment: 
    - RABBITMQ_DEFAULT_USER=roboshop 
    - RABBITMQ_DEFAULT_PASS=roboshop123


  payment:
    image: nishaldevops/payment:v1
    container_name: payment
    networks:
    - roboshop
    depends_on:
      - shipping
      - rabbitmq
  
  web:
    image: nishaldevops/web:v1
    container_name: web
    networks:
    - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
 