
# Run this commad directly in CLI no need to write any docker file and config file for this. This is the 
# simple installation of redis So, we can run in CLI 


# docker run -d --name redis --network roboshop redis